### ISSUE TITLE
BBR Unable to backup Bosh Director using mysql 8.0.x

### ISSUE THREAD

**Issue by git-pcs** [cloudfoundry/backup-and-restore-sdk-release#681]
Hi,

I am getting the error below when backing up Bosh director using external mysql db version 8.0.x.
From the Readme, I understand 8.0.X is supported?
Appreciate any guidance in this matter.

Error attempting to run backup for job director on bosh/0: 2022/08/10 07:42:18 MYSQL server version 8.0.28
2022/08/10 07:42:18 unsupported version of mysql: 8.0 - exit code 1

**Comment by totherme** [comment]
We do now support mysql 8, so this should work now. Thanks!
